### ISSUE TITLE
Build fails on jdk 17 due to invalid flag

### ISSUE THREAD

**Issue by virustotalop** [magicmq/pyspigot#3]
**Describe the bug**
Build fails when using jdk 17 due to the invalid command line argument `--no-module-directories` 

**To Reproduce**
1. Use jdk 17
2. Run maven clean
3. Run maven package
4. Error occurs due to invalid `--no-module-directories` command line flag

**Expected behavior**
Even though the plugin targets java 11 it should be able to be compiled with java 17

**Screenshots**
![image](https://github.com/magicmq/pyspigot/assets/11567285/062ce006-2680-42f6-aec8-94979b852131)

**Additional Info (please fill in):**
 - Server environment: Paper
 - Minecraft version 1.20.4
 - PySpigot version 0.5.1

**Additional context**
It looks like this flag was removed in java 13

https://bugs.openjdk.org/browse/JDK-8215582
https://stackoverflow.com/questions/46118716/fatal-error-compiling-invalid-flag-module-path
https://github.com/amaembo/streamex/issues/247

**Comment by magicmq** [comment]
This flag was originally added in due to a nonfunctional search bar in the generated JavaDocs when building the project with JDK 11 (910211a4f11f8770dd4235024de2576616b8a213). Removing the flag allows for building the project on JDK 17 and the search bar in the generated JavaDocs is functional, so all is good.
